# Generated by Leamas from factory-core-v1.
# Do not edit this file directly.

include .factory/generated/factory.mk

# Native gate prerequisites will be introduced by later ACTs

.PHONY: gate
gate: factorize
