# Generated by Leamas from factory-core-v1.
# Do not edit this file directly.

include .factory/generated/factory.mk

# =============================================================================
# Tool paths (overridable)
# =============================================================================
DOTNET  ?= dotnet
NPM     ?= npm
DEV_BOOTSTRAP_ARGS ?=
CONTAINER_CLI ?= docker
CONTAINER_PLATFORM ?= linux/amd64
SLN      := Circus.sln
WEB_DIR  := web
WEB_DIST := $(WEB_DIR)/dist
CONTAINER_BACKEND_IMAGE ?= circus-backend:act-local
CONTAINER_FRONTEND_IMAGE ?= circus-frontend:act-local
CONTAINER_SOURCE_REVISION := $(shell git rev-parse HEAD 2>/dev/null || printf 'local')
CONTAINER_CREATED := $(shell git show -s --format=%cI HEAD 2>/dev/null || printf '1970-01-01T00:00:00Z')

# Sources that should trigger an Elm rebuild.
WEB_SOURCES := \
    $(WEB_DIR)/elm.json \
    $(WEB_DIR)/package.json \
    $(WEB_DIR)/package-lock.json \
    $(WEB_DIR)/index.html \
    $(WEB_DIR)/styles.css \
    $(wildcard $(WEB_DIR)/src/*.elm)

# =============================================================================
# Restore
# =============================================================================

.PHONY: restore
restore: dotnet-tool-restore dotnet-restore-locked npm-ci

# =============================================================================
# .NET environment check (ACT-CIRCUS-DOTNET-USER-PATH-PERSISTENCE01)
# =============================================================================

.PHONY: dotnet-env-check
dotnet-env-check:
	@command -v dotnet >/dev/null 2>&1 || { \
		echo "ERROR: dotnet is installed but is not visible in PATH, or is absent."; \
		echo "Run ACT-CIRCUS-DOTNET-USER-PATH-PERSISTENCE01 diagnostics."; \
		exit 2; \
	}
	@dotnet --version
	@dotnet --list-sdks

.PHONY: dotnet-tool-restore
dotnet-tool-restore:
	$(DOTNET) tool restore

.PHONY: dotnet-restore-locked
dotnet-restore-locked:
	$(DOTNET) restore $(SLN) --locked-mode

.PHONY: npm-ci
npm-ci:
	cd $(WEB_DIR) && $(NPM) ci

# =============================================================================
# Format (mutating; must not run inside factorize or gate)
# =============================================================================

.PHONY: format
format: dotnet-tool-restore npm-ci
	$(DOTNET) fantomas src/ tests/
	cd $(WEB_DIR) && ./node_modules/.bin/elm-format src tests --yes

.PHONY: format-check
format-check: restore
	$(DOTNET) fantomas --check src/ tests/
	cd $(WEB_DIR) && ./node_modules/.bin/elm-format src tests --validate

# =============================================================================
# Backend build and test
# =============================================================================

.PHONY: build-backend
build-backend: restore
	$(DOTNET) build $(SLN) -c Release --no-restore

.PHONY: test-domain
test-domain: build-backend
	$(DOTNET) run --project tests/Circus.Domain.Tests -c Release --no-build --no-restore

.PHONY: test-contracts
test-contracts: build-backend
	$(DOTNET) run --project tests/Circus.Contracts.Tests -c Release --no-build --no-restore

.PHONY: test-application
test-application: build-backend
	$(DOTNET) run --project tests/Circus.Application.Tests -c Release --no-build --no-restore

# PostgreSQL tests require a running Docker-compatible daemon for Testcontainers
.PHONY: test-postgres
test-postgres: build-backend
	@if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then \
		:; \
	elif command -v podman >/dev/null 2>&1 && podman info >/dev/null 2>&1 && test -n "$$DOCKER_HOST"; then \
		:; \
	else \
		echo "ERROR: PostgreSQL integration evidence requires a running Docker-compatible daemon."; \
		echo "Start Docker Desktop or Podman with a Docker-compatible socket, then rerun 'make test-backend'."; \
		exit 1; \
	fi
	$(DOTNET) run --project tests/Circus.Persistence.Postgres.Tests -c Release --no-build --no-restore

.PHONY: test-api
test-api: build-backend
	$(DOTNET) run --project tests/Circus.Api.Tests -c Release --no-build --no-restore

.PHONY: test-devhost
test-devhost: build-backend
	$(DOTNET) run --project tests/Circus.DevHost.Tests -c Release --no-build --no-restore

.PHONY: test-backend
test-backend: build-backend
	$(DOTNET) run --project tests/Circus.Domain.Tests   -c Release --no-build --no-restore
	$(DOTNET) run --project tests/Circus.Contracts.Tests -c Release --no-build --no-restore
	$(DOTNET) run --project tests/Circus.Application.Tests -c Release --no-build --no-restore
	$(MAKE) test-postgres
	$(DOTNET) run --project tests/Circus.Api.Tests      -c Release --no-build --no-restore

# =============================================================================
# Web build and test
# =============================================================================

.PHONY: build-web
build-web: $(WEB_DIST)/app.js

$(WEB_DIST)/app.js: $(WEB_SOURCES) | npm-ci
	mkdir -p $(WEB_DIST)
	cd $(WEB_DIR) && ./node_modules/.bin/elm make src/Main.elm --optimize --output=dist/app.js
	cp $(WEB_DIR)/index.html $(WEB_DIR)/styles.css $(WEB_DIST)/

$(WEB_DIST):
	mkdir -p $(WEB_DIST)

.PHONY: test-web
test-web: npm-ci
	cd $(WEB_DIR) && ./node_modules/.bin/elm-test --compiler ./node_modules/.bin/elm

# =============================================================================
# Composite targets
# =============================================================================

.PHONY: build
build: build-backend build-web

.PHONY: test
test: test-backend test-web

.PHONY: test-ingestion
test-ingestion: test-application test-postgres test-api

# =============================================================================
# Container images and runtime smoke tests
# =============================================================================

.PHONY: verify-container-policy
verify-container-policy: build-source-policy
	$(CIRCUS_TOOLING) container-policy verify

.PHONY: container-build-backend
container-build-backend:
	DOCKER_BUILDKIT=1 $(CONTAINER_CLI) build --platform $(CONTAINER_PLATFORM) --file Dockerfile.backend --tag $(CONTAINER_BACKEND_IMAGE) \
		--build-arg OCI_TITLE="The Circus backend" \
		--build-arg OCI_DESCRIPTION="The Circus production backend OCI image" \
		--build-arg OCI_SOURCE="local://thecircus" \
		--build-arg OCI_REVISION=$(CONTAINER_SOURCE_REVISION) \
		--build-arg OCI_VERSION=act-local \
		--build-arg OCI_CREATED=$(CONTAINER_CREATED) .

.PHONY: container-build-frontend
container-build-frontend:
	DOCKER_BUILDKIT=1 $(CONTAINER_CLI) build --platform $(CONTAINER_PLATFORM) --file Dockerfile.frontend --tag $(CONTAINER_FRONTEND_IMAGE) \
		--build-arg OCI_TITLE="The Circus frontend" \
		--build-arg OCI_DESCRIPTION="The Circus production frontend OCI image" \
		--build-arg OCI_SOURCE="local://thecircus" \
		--build-arg OCI_REVISION=$(CONTAINER_SOURCE_REVISION) \
		--build-arg OCI_VERSION=act-local \
		--build-arg OCI_CREATED=$(CONTAINER_CREATED) .

.PHONY: container-smoke-backend
container-smoke-backend: container-build-backend
	CONTAINER_CLI=$(CONTAINER_CLI) scripts/container-smoke.sh backend $(CONTAINER_BACKEND_IMAGE)

.PHONY: container-smoke-frontend
container-smoke-frontend: container-build-frontend
	CONTAINER_CLI=$(CONTAINER_CLI) scripts/container-smoke.sh frontend $(CONTAINER_FRONTEND_IMAGE)

.PHONY: container-smoke
container-smoke: container-smoke-backend container-smoke-frontend
	@echo "Container smoke tests passed."

# =============================================================================
# Run
# =============================================================================

.PHONY: run
run: build-backend
	$(DOTNET) run --project src/Circus.Api -c Release --no-build --no-restore

# =============================================================================
# Smoke (single shell transaction)
# =============================================================================

.PHONY: smoke
smoke: build-backend build-web
	bash scripts/smoke.sh

# =============================================================================
# Clean
# =============================================================================

.PHONY: clean
clean:
	$(DOTNET) build $(SLN) --no-restore -t:Clean 2>/dev/null || true
	cd $(WEB_DIR) && rm -rf dist elm-stuff
	find . -type d \( -name bin -o -name obj -o -name TestResults \) -exec rm -rf {} + 2>/dev/null || true


# =============================================================================
# Source policy (ML-only F#/Elm enforcement) — ACT-CIRCUS-ML-ONLY-SOURCE-POLICY01
# =============================================================================

# RID-neutral framework-dependent invocation.  The canonical artefact is
# ``circus-tooling.dll``; running it through ``dotnet`` keeps the path
# portable across host operating systems and avoids depending on the
# RID-specific native apphost (``circus-tooling`` on Linux,
# ``circus-tooling.exe`` on Windows, etc.).  See
# ACT-CIRCUS-ML-ONLY-SOURCE-POLICY01-CORRECTION03.
CIRCUS_TOOLING_DLL := tools/Circus.Tooling/bin/Release/net10.0/circus-tooling.dll
CIRCUS_TOOLING     := $(DOTNET) $(CIRCUS_TOOLING_DLL)

.PHONY: build-source-policy
build-source-policy:
	$(DOTNET) build tools/Circus.Tooling/Circus.Tooling.fsproj -c Release

.PHONY: source-policy
source-policy: build-source-policy
	$(CIRCUS_TOOLING) source-policy verify

.PHONY: source-policy-json
source-policy-json: build-source-policy
	$(CIRCUS_TOOLING) source-policy verify --format json

.PHONY: test-source-policy
test-source-policy: build-source-policy
	$(DOTNET) run --project tests/Circus.Tooling.Tests/Circus.Tooling.Tests.fsproj -c Release --no-restore -- --summary

# =============================================================================
# Native gate
# =============================================================================

.PHONY: gate
gate: factorize format-check test-backend test-devhost test-web smoke
	@echo "=== Native gate passed ==="

# =============================================================================
# Linux development environment (ACT-CIRCUS-LINUX-DEV-HOST-BOOTSTRAP01)
# =============================================================================

# Bootstrap the Linux development environment through the typed F# authority.
.PHONY: dev-bootstrap-linux
dev-bootstrap-linux:
	./scripts/circus-dev bootstrap $(DEV_BOOTSTRAP_ARGS)

# Check prerequisites only (no installation)
.PHONY: dev-bootstrap-check-linux
dev-bootstrap-check-linux:
	./scripts/circus-dev check

.PHONY: dev-activate-help
dev-activate-help:
	@echo 'Run: eval "$$(./scripts/circus-dev env)"'

.PHONY: dev-doctor
dev-doctor:
	./scripts/circus-dev doctor

.PHONY: dev-restore
dev-restore:
	$(DOTNET) restore $(SLN) --locked-mode
	cd $(WEB_DIR) && $(NPM) ci

.PHONY: dev-test-linux
dev-test-linux:
	$(MAKE) format-check
	$(MAKE) test-domain
	$(MAKE) test-contracts
	$(MAKE) test-application
	$(MAKE) test-web
	$(MAKE) test-postgres
	$(MAKE) test-api
	$(MAKE) test-devhost

.PHONY: dev-container-smoke
dev-container-smoke:
	$(MAKE) CONTAINER_CLI=docker CONTAINER_PLATFORM=linux/amd64 container-smoke

# dev-gate-linux is intentionally a single F# command.  The
# circus-tooling gate run runner executes every canonical local check
# exactly once, regenerates the gate-summary artefact, and validates
# the resulting JSON against the Leamas v1 wire contract.  See
# ACT-CIRCUS-ML-ONLY-SOURCE-POLICY01-CORRECTION02 and
# ACT-CIRCUS-ML-ONLY-SOURCE-POLICY01-CORRECTION03.
.PHONY: dev-gate-linux
dev-gate-linux: build-source-policy
	$(CIRCUS_TOOLING) gate run

# =============================================================================
# No-force-push verification (ACT-CIRCUS-NO-FORCE-PUSH-DOCTRINE-GATE01)
# =============================================================================

.PHONY: no-force-push
no-force-push: build-source-policy
	$(CIRCUS_TOOLING) no-force-push verify

.PHONY: test-no-force-push
test-no-force-push: build-source-policy
	$(DOTNET) run --project tests/Circus.Tooling.Tests/Circus.Tooling.Tests.fsproj -c Release --no-restore -- --focus "NoForcePush"

.PHONY: install-git-safety-hooks
install-git-safety-hooks:
	@hooks_path=".githooks"; \
	if [ -d ".git/hooks" ]; then \
		git config core.hooksPath "$$hooks_path"; \
		echo "Git safety hooks installed at: $$hooks_path"; \
		git config --local --get core.hooksPath; \
	else \
		echo "ERROR: Not in a git repository"; \
		exit 1; \
	fi

.PHONY: verify-github-no-force-push
verify-github-no-force-push:
	$(CIRCUS_TOOLING) no-force-push github-rules verify --repository s1onique/thecircus --branch main

.PHONY: publication-gate
publication-gate: build-source-policy
	$(CIRCUS_TOOLING) no-force-push verify
	$(MAKE) verify-github-no-force-push
