<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Circus.Persistence.Postgres.Tests.Runner</RootNamespace>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="PostgresTestRunner.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Expecto" />
  </ItemGroup>

</Project>
